FROM node:lts-alpine3.15

# install simple http server for serving static content
RUN npm install --location=global http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY ../client .

# install project dependencies
RUN npm install

# build app for production with minification
RUN npm run build

EXPOSE 8081
CMD [ "http-server", "dist" ]